### ISSUE TITLE
用了之后提示A non-empty request body is required

### ISSUE THREAD

**Issue by qcjxberin** [yangzhongke/YouZack.FromJsonBody#1]
用了之后提示A non-empty request body is required

**Comment by yangzhongke** [comment]
您是不是在Get请求上设置content-type: application/json了？
只有Post请求才能设置content-type: application/json
具体请参考这个
[https://github.com/dotnet/aspnetcore/issues/27315](https://github.com/dotnet/aspnetcore/issues/27315)
